name: Next js Deploy To Cloudfront
on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Deploy
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm deploy
